import Nav from '@/components/nav'
import './globals.css'
import { Changa, Dancing_Script } from 'next/font/google'
import Link from 'next/link'

const changa = Changa({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-changa',
})

const dancing = Dancing_Script({
    subsets: ['latin'],
    display: 'swap',
    variable: '--font-dancing',
})

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
}

export default function Layout({ children }: { children: React.ReactNode }) {
    return (
        <main className={`${changa.variable} ${dancing.variable} font-changa bg-bgcol text-textcol relative`}>
            <Nav />
            {children}
            <div className="absolute bottom-2 w-full text-center">
                <Link href="https://www.owengretzinger.com" target="_blank" className="text-textcol/30">
                    Designed & Built by Owen Gretzinger
                </Link>
            </div>

        </main>
    )
}